// Generates a standalone stdio MCP server from a no-code tool definition.

export type BuilderParam = { name: string; type: string; description: string; required: boolean };
export type BuilderTool = {
  name: string;
  description: string;
  params: BuilderParam[];
  execution:
    | { type: "http"; method: "GET" | "POST"; url: string }
    | { type: "shell"; command: string }
    | { type: "js"; code: string };
};
export type BuilderServer = { name: string; description: string; tools: BuilderTool[] };

export function generateServerCode(server: BuilderServer): string {
  const toolDefs = server.tools.map((t) => {
    const props = t.params
      .map((p) => `        ${JSON.stringify(p.name)}: { type: ${JSON.stringify(p.type)}, description: ${JSON.stringify(p.description)} }`)
      .join(",\n");
    const required = t.params.filter((p) => p.required).map((p) => JSON.stringify(p.name)).join(", ");
    return `  {
    name: ${JSON.stringify(t.name)},
    description: ${JSON.stringify(t.description)},
    inputSchema: {
      type: "object",
      properties: {
${props}
      },
      required: [${required}]
    }
  }`;
  }).join(",\n");

  const handlers = server.tools.map((t) => {
    let body = "";
    if (t.execution.type === "http") {
      body = `      const url = ${JSON.stringify(t.execution.url)}.replace(/\\{(\\w+)\\}/g, (_, k) => args[k] ?? "");
      const res = await fetch(url, { method: ${JSON.stringify(t.execution.method)}, ${t.execution.method === "POST" ? "body: JSON.stringify(args), headers: { 'content-type': 'application/json' }" : ""} });
      output = await res.text();`;
    } else if (t.execution.type === "shell") {
      body = `      const { execSync } = await import("node:child_process");
      let cmd = ${JSON.stringify(t.execution.command)};
      for (const [k, v] of Object.entries(args)) cmd = cmd.split("{" + k + "}").join(String(v));
      output = execSync(cmd, { encoding: "utf8", timeout: 30000 });`;
    } else {
      body = `      const fn = new Function("args", ${JSON.stringify(t.execution.code)});
      output = String(await fn(args));`;
    }
    return `  if (name === ${JSON.stringify(t.name)}) {
    try {
${body}
    } catch (e) {
      return { content: [{ type: "text", text: "Error: " + e.message }], isError: true };
    }
    return { content: [{ type: "text", text: String(output) }] };
  }`;
  }).join("\n");

  return `#!/usr/bin/env node
// Generated by LocalMind MCP Server Builder — ${server.name}
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";

const TOOLS = [
${toolDefs}
];

const server = new Server({ name: ${JSON.stringify(server.name)}, version: "1.0.0" }, { capabilities: { tools: {} } });

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }));

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args = {} } = req.params;
  let output = "";
${handlers}
  return { content: [{ type: "text", text: "Unknown tool: " + name }], isError: true };
});

const transport = new StdioServerTransport();
await server.connect(transport);
`;
}
