/**
 * POST /api/fleet/pair/accept
 *
 * Responder flow: user paste / scan the initiator's pairing payload. This
 * route validates the payload structurally, dials the initiator's fleet port
 * over TLS pinned by the cert fingerprint in the payload, sends a
 * `pair-confirm` envelope carrying everything the initiator needs to record
 * us. On success, we record the initiator in our own fleet_peers table.
 *
 * Body:
 *   {
 *     payload_json: string | object,   // pasted JSON, or already-parsed object
 *     label_for_initiator?: string,    // friendly name we want for the initiator
 *   }
 *
 * Response:
 *   { ok: true, peer: FleetPeer, initiator_node_id: string }
 *   or { ok: false, reason }
 */

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import os from "os";
import { decodePayload } from "@/lib/fleet/pairing";
import { sendUnpaired } from "@/lib/fleet/peer-client";
import { pairPeer, recordCapabilities, getPeer } from "@/lib/db/fleet";
import { getNodeIdentity, exportPublicKey } from "@/lib/fleet/identity";
import { getTlsMaterial } from "@/lib/fleet/tls";
import { activeFleetPort, isRunning, listenerDownMessage } from "@/lib/fleet/server";

export const runtime = "nodejs";

const Body = z.object({
  payload_json: z.union([z.string(), z.record(z.unknown())]),
  label_for_initiator: z.string().min(1).max(80).optional(),
});

function detectOwnPrimaryAddr(): string {
  const port = activeFleetPort() ?? Number(process.env.LOCALMIND_FLEET_PORT || 9443);
  const ifaces = os.networkInterfaces();
  for (const list of Object.values(ifaces)) {
    if (!list) continue;
    for (const a of list) {
      if (a.family === "IPv4" && !a.internal) return `${a.address}:${port}`;
    }
  }
  return `127.0.0.1:${port}`;
}

export async function POST(req: NextRequest) {
  if (!isRunning()) {
    return NextResponse.json(
      // This guard is about THIS device. The old copy said "both devices need
      // the listener up", which sent people looking at the wrong machine.
      { error: `${listenerDownMessage()} Pairing needs the listener up on this device.` },
      { status: 503 }
    );
  }

  const parsed = Body.safeParse(await req.json().catch(() => ({})));
  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid accept payload." }, { status: 400 });
  }

  const raw =
    typeof parsed.data.payload_json === "string"
      ? parsed.data.payload_json
      : JSON.stringify(parsed.data.payload_json);
  const decoded = decodePayload(raw);
  if (!decoded.ok) return NextResponse.json({ error: decoded.reason }, { status: 400 });
  const p = decoded.payload;

  // Don't accept pairing-with-self (helpful for the loopback self-test, which
  // bypasses this guard explicitly).
  if (p.node_id === getNodeIdentity().node_id && !req.nextUrl.searchParams.get("allow_self")) {
    return NextResponse.json(
      { error: "Pairing payload was generated by this same node." },
      { status: 400 }
    );
  }

  // Already paired? Refuse the duplicate, but report which peer matches so
  // the UI can show "already paired as X".
  const existing = getPeer(p.node_id);
  if (existing) {
    return NextResponse.json(
      {
        error: `Already paired with ${p.node_id} (${existing.label ?? "no label"}). Unpair first to re-pair.`,
        already_paired: true,
        peer: existing,
      },
      { status: 409 }
    );
  }

  // Parse host:port for the dial-back.
  const [host, portStr] = p.primary_addr.includes(":")
    ? p.primary_addr.split(":", 2)
    : [p.primary_addr, String(Number(process.env.LOCALMIND_FLEET_PORT || 9443))];
  const port = Number(portStr);
  if (!host || !Number.isFinite(port)) {
    return NextResponse.json({ error: `Invalid primary_addr in payload: ${p.primary_addr}` }, { status: 400 });
  }

  const tls = getTlsMaterial();
  const me = getNodeIdentity();

  const confirmPayload = {
    pairing_token: p.pairing_token,
    node_id: me.node_id,
    pubkey_pem: exportPublicKey(),
    cert_fingerprint_sha256: tls.fingerprint_sha256,
    cert_pem: tls.cert_pem,
    primary_addr: detectOwnPrimaryAddr(),
    label_for_initiator: parsed.data.label_for_initiator,
  };

  const result = await sendUnpaired<typeof confirmPayload, { ack: true; initiator_label?: string }>(
    host,
    port,
    p.cert_fingerprint_sha256,
    p.pubkey_pem,
    p.node_id,
    "pair-confirm",
    confirmPayload,
    { timeoutMs: 10_000 }
  );

  if (!result.ok) {
    return NextResponse.json({ error: `Pairing call failed: ${result.reason}` }, { status: 502 });
  }

  // Initiator accepted. Mirror the peer row on our side. Their pubkey + cert
  // came from the QR payload, so we can pin both immediately.
  pairPeer({
    peer_node_id: p.node_id,
    pubkey_pem: p.pubkey_pem,
    label: parsed.data.label_for_initiator ?? p.label_hint ?? null,
    primary_addr: p.primary_addr,
  });
  // We don't have the initiator's cert PEM from the QR (only its fingerprint),
  // so we can't pin via the `ca` list yet. Fetch their cert by hitting /fleet/health
  // over TLS without rejection and then verifying the fingerprint matches.
  try {
    const https = await import("https");
    const certPem = await new Promise<string | null>((resolve) => {
      const req = https.request(
        {
          host,
          port,
          path: "/fleet/health",
          method: "GET",
          rejectUnauthorized: false,
          checkServerIdentity: () => undefined,
          timeout: 4000,
        },
        (res) => {
          const sock = res.socket as import("tls").TLSSocket;
          const cert = sock.getPeerCertificate(true);
          // Confirm fingerprint matches what the QR said.
          const presented = (cert.fingerprint256 || "").replace(/:/g, "").toLowerCase();
          if (presented !== p.cert_fingerprint_sha256.toLowerCase()) {
            resolve(null);
            return;
          }
          const der = cert.raw;
          const b64 = der.toString("base64").match(/.{1,64}/g)?.join("\n") ?? "";
          resolve(`-----BEGIN CERTIFICATE-----\n${b64}\n-----END CERTIFICATE-----\n`);
          res.resume();
        }
      );
      req.on("error", () => resolve(null));
      req.on("timeout", () => { req.destroy(); resolve(null); });
      req.end();
    });
    if (certPem) {
      recordCapabilities(p.node_id, {
        tls_cert_pem: certPem,
        tls_fingerprint_sha256: p.cert_fingerprint_sha256,
      });
    }
  } catch {
    // Non-fatal — heartbeat will repopulate capabilities. Pinning the cert
    // can wait for the next round-trip; at worst the first heartbeat fails
    // and the next /pair/accept call reseeds it.
  }

  return NextResponse.json({
    ok: true,
    peer: getPeer(p.node_id),
    initiator_node_id: p.node_id,
  });
}
